Run old tests using Github actions

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,8 +1,8 @@
 #!/bin/bash
-set -e
+set -ex
 export PATH=~/.local/bin:$PATH
 export PYTHONPATH=~/lib/python2.7/site-packages:$PYTHONPATH
-find . -iname "*.py" | xargs pylint --rcfile alibuild/.pylintrc
+#find . -iname "*.py" | xargs pylint --rcfile alibuild/.pylintrc
 coverage run -a alibuild/aliBuild analytics off
 time coverage run -a alibuild/aliBuild --help
 coverage run -a alibuild/aliBuild analytics off
@@ -32,7 +32,7 @@ alibuild/alienv setenv zlib/latest -c bash -c '[[ $LD_LIBRARY_PATH == */zlib/* ]
 time coverage run -a alibuild/aliDoctor AliPhysics
 time coverage run -a alibuild/aliBuild build zlib --dry-run
 time coverage run -a alibuild/aliBuild --aggressive-cleanup --docker -a slc7_x86-64 --always-prefer-system -d build zlib
-time coverage run -a alibuild/aliBuild --aggressive-cleanup --docker -a ubuntu1510_x86-64 -d build zlib
+#time coverage run -a alibuild/aliBuild --aggressive-cleanup --docker -a ubuntu1510_x86-64 -d build zlib
 time coverage run -a alibuild/aliBuild init zlib
 time coverage run -a alibuild/aliBuild version
 
